### ISSUE TITLE
您好，为什么http的请求全部扔到task去处理呢，这样做的好处是什么，还有子进程退出的时候我看你那块代码没写完，你讲讲你的思路吧，感谢

### ISSUE THREAD

**Issue by baoqianduan666** [xinliangnote/Swoole#1]
您好，为什么http的请求全部扔到task去处理呢，这样做的好处是什么，还有子进程退出的时候我看你那块代码没写完，你讲讲你的思路吧，感谢

**Comment by xinliangnote** [comment]
1. 为什么http的请求全部扔到task去处理？
这个是仅仅为了实现 task 异步，具体好处看业务吧。如果业务比较单一，需要同步执行的话，也可以开启多个Worker进程，进行处理。
2. 关于子进程退出的时候，没写完问题。
这块打算做成，当接到不同的信号做不同的处理，`Process::signal`，比如接到 ctrl+c 就退出 等等，这块当时未实现。
